// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-layouts/ActivityFeed.tsx": () => import("../components/mockups/dashboard-layouts/ActivityFeed.tsx"),
  "./components/mockups/dashboard-layouts/CleanList.tsx": () => import("../components/mockups/dashboard-layouts/CleanList.tsx"),
  "./components/mockups/dashboard-layouts/TabbedView.tsx": () => import("../components/mockups/dashboard-layouts/TabbedView.tsx")
};
